import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Menu from "./components/menu";
import Perfil from "./components/perfil";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Renê Dev | Front-End",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="">
              <div className="">
                <Menu />
              </div>
              <div className="gap-8 lg:grid lg:grid-cols-[350px_1fr] lg:items-start">
                <div className="">
                  <Perfil />
                </div>
                <div className="">
                  {children}
                </div>
              </div>
            </div>
      </body>
    </html>
  );
}
